#spring:
#  main:
#    banner-mode: "off" #it is used to off the banner which is always showing on startup

# Common Kafka Properties
# auto:
#   create:
#     topics:
#       enable: true
# auto.create.topics.enable=true
topic:
  name: test


app:
  message: This is the dev Environment property file

spring:
  application:
    name: This is dev kafka producer
  output:
    ansi:
      enabled: always
  # kafka:
  #   producer:
  #     bootstrap-servers: localhost:9092
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #   consumer:
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     group-id: myGroup
  #     auto-offset-reset: earliest
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 9002
  address: 127.0.0.1


logging:
  level:
      root: ERROR
      com.kafkapublisher.KafkaPublisher: INFO
  # pattern:
  #   console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/dev.log
    max-history: 30
    max-size: 10MB
  
